log_dir: /NAGRpj/log/dbrp/
log_level: DEBUG
db_config: /NAGRpj/cfg/db.yaml
parallel_tasks: False

monitor:
  handler_class: etl.monitors.DBRPMonitorHandler
  db_config_label: ***
  table_name: ***
  import_mode: insert


tasks:
-
  id: ***
  group: ***
  task_class: etl.tasks.TimedDBTask
  extractions:
    extraction_class: etl.extractions.TimedDBExtraction
    db_config_label: ***
    table_name: ***
    time_column:
      name: DTIME
      time_delta: -2 minutes
  transformation:
    transformation_class: etl.transformations.NoneTransformation
  writings:
    loading_class: etl.writings.CountedDBLoading
    db_config_label: 172.16.9.211/NAGRdb
    table_name: web_asos_min
    import_mode: replace

-
  id: ***
  group: ***
  task_class: etl.tasks.TimedDBTask
  extractions:
    extraction_class: etl.extractions.TimedDBExtraction
    db_config_label: ***
    table_name: ***
    time_column:
      name: DTIME
      time_delta: -6 minutes
  transformation:
    transformation_class: etl.transformations.NoneTransformation
  writings:
    loading_class: etl.writings.CountedDBLoading
    db_config_label: ***
    table_name: ***
    import_mode: replace
